
//Operator Management Action Types
export const ADD_OPERATOR = "ADD_OPERATOR"
export const EDIT_OPERATOR = "EDIT_OPERATOR"
export const REMOVE_OPERATOR = "REMOVE_OPERATOR"
export const UNDO_REMOVE_OPERATOR = "UNDO_REMOVE_OPERATOR"

//Line Management Action Types
export const ADD_LINE = "ADD_LINE"
export const EDIT_LINE = "EDIT_LINE"
export const REMOVE_LINE = "REMOVE_LINE"
export const UNDO_REMOVE_LINE = "UNDO_REMOVE_LINE"

//Service Management Action Types
export const ADD_SERVICE = "ADD_SERVICE"
export const EDIT_SERVICE = "EDIT_SERVICE"
export const REMOVE_SERVICE = "REMOVE_SERVICE"
export const UNDO_REMOVE_SERVICE = "UNDO_REMOVE_SERVICE"

//Service-Track Action Types
export const ADD_SERVICETRACK_TWOWAY = "ADD_SERVICETRACK_TWOWAY"
export const ADD_SERVICETRACK_ONEWAY = "ADD_SERVICETRACK_ONEWAY"
export const SWITCH_ONEWAY_DIRECTION = "SWITCH_ONEWAY_DIRECTION"
export const TWOWAY_TO_ONEWAY = "TWOWAY_TO_ONEWAY"
export const REMOVE_SERVICE_TRACK = "REMOVE_SERVICE_TRACK"
export const UNREMOVE_SERVICE_TRACK = "UNREMOVE_SERVICE_TRACK"
export const REMOVE_SERVICE_TRACK_BLOCK = "REMOVE_SERVICE_TRACK"
export const UNDO_REMOVE_SERVICE_TRACK_BLOCK = "UNDO_REMOVE_SERVICE_TRACK"
export const REMOVE_STOP = "REMOVE_STOP"
export const UNDO_REMOVE_STOP = "UNDO_REMOVE_STOP"

//Node Action Types
export const ADD_NODE = "ADD_NODE"
export const EDIT_NODE = "EDIT_NODE" // MOVE NODE
export const REMOVE_NODE = "REMOVE_NODE"
export const UNDO_REMOVE_NODE = "UNDO_REMOVE_NODE"

