

export const ADD_OPERATOR = "ADD_OPERATOR"
export const EDIT_OPERATOR = "EDIT_OPERATOR"
export const REMOVE_OPERATOR = "REMOVE_OPERATOR"
export const UNDO_REMOVE_OPERATOR = "UNDO_REMOVE_OPERATOR"

export const ADD_LINE = "ADD_LINE"
export const EDIT_LINE = "EDIT_LINE"
export const REMOVE_LINE = "REMOVE_LINE"
export const UNDO_REMOVE_LINE = "UNDO_REMOVE_LINE"

export const ADD_SERVICE = "ADD_SERVICE"
export const EDIT_SERVICE = "EDIT_SERVICE"
export const REMOVE_SERVICE = "REMOVE_SERVICE"
export const UNDO_REMOVE_SERVICE = "UNDO_REMOVE_SERVICE"