export const ALWAYS = "ALWAYS"
export const WEEKDAYS_ONLY = "WEEKDAYS_ONLY"
export const WEEKEND_ONLY = "WEEKEND_ONLY"
export const RUSH_HOUR_ONLY = "RUSH_HOUR_ONLY"
export const PEAK_ONLY = "PEAK_ONLY"
export const LIMITED = "LIMITED"